name: lemonade
description: O navegador sem frescuras com ferramentas de dev.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^6.0.0
  firebase_core: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/logo.png"
  adaptive_icon_background: "#121212" # Cor escura de fundo para combinar com o limão neon

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
