name: Build Lemonade APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o codigo do repositorio
      uses: actions/checkout@v4

    - name: Configurar o Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Configurar o Flutter Estavel
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'

    - name: Restaurar e Corrigir Estrutura Nativa (Garante Bolinha Verde)
      run: |
        # Cria backups de seguranca
        mkdir -p backup_lemonade
        cp lib/main.dart backup_lemonade/
        cp pubspec.yaml backup_lemonade/
        
        # Apaga a pasta nativa antiga
        rm -rf android
        
        # Cria o projeto de forma limpa e perfeita
        flutter create . --org com.error404notafound --project-name lemonade
        
        # Restaura seus arquivos principais intactos
        cp backup_lemonade/main.dart lib/
        cp backup_lemonade/pubspec.yaml ./
        
        # Ativa o AndroidX
        echo "android.useAndroidX=true" >> android/gradle.properties
        echo "android.enableJetifier=true" >> android/gradle.properties

    - name: Configurar Forcado para Android 5.0+ e Injetar Permissoes
      run: |
        # Usamos Python para ajustar a versao minima exigida pelo Firebase e injetar o Cleartext
        python3 -c "
        # 1. Ajusta o minSdkVersion para 21
        build_gradle_path = 'android/app/build.gradle'
        with open(build_gradle_path, 'r') as f:
            bg_content = f.read()
        bg_content = bg_content.replace('minSdkVersion flutter.minSdkVersion', 'minSdkVersion 21')
        with open(build_gradle_path, 'w') as f:
            f.write(bg_content)

        # 2. Injeta a regra que aceita sites HTTP antigos
        manifest_path = 'android/app/src/main/AndroidManifest.xml'
        with open(manifest_path, 'r') as f:
            m_content = f.read()
        if 'android:usesCleartextTraffic' not in m_content:
            m_content = m_content.replace('<application', '<application android:usesCleartextTraffic=\"true\"')
        with open(manifest_path, 'w') as f:
            f.write(m_content)
        "

    - name: Baixar as dependencias do app
      run: flutter pub get

    - name: Criar o arquivo APK Final
      run: flutter build apk --debug

    - name: Disponibilizar o APK para Download
      uses: actions/upload-artifact@v4
      with:
        name: lemonade-app-apk
        path: build/app/outputs/flutter-apk/app-debug.apk
